CONTAINER Ocifreader
{
	NAME Ocifreader;
	INCLUDE Obase;
	GROUP ID_OBJECTPROPERTIES
	{
		FILENAME ID_CIF_PATH {}
		LONG ID_CIF_A { MIN -20; MAX 20; STEP 1;}
		LONG ID_CIF_B { MIN -20; MAX 20; STEP 1;}
		LONG ID_CIF_C { MIN -20; MAX 20; STEP 1;}
		LONG ID_CIF_CENTER_TYPE
		{
			CUSTOMGUI QUICKTABRADIO;
			CYCLE
			{
				ID_CIF_CENTER_TYPE_GUESS;
				ID_CIF_CENTER_TYPE_SYMBOL;
				ID_CIF_CENTER_TYPE_LABEL;
			}
		}
		STRING ID_CIF_POLY_CENTER {}
		BUTTON ID_CIF_UPDATE {}

		REAL ID_CIF_ATOM_RADIUS_SCALE { MIN 0.0; MAX 5.0; STEP 0.1;}
		LONG ID_CIF_ATOM_SEGMENTS { MIN 3; MAX 50;}
		REAL ID_CIF_BOND_RADIUS { MIN 0.0; MAX 5.0; STEP 0.1;}
		BOOL ID_CIF_SHOW_CELL {}
		BOOL ID_CIF_SHOW_BOND {}
		BOOL ID_CIF_SHOW_POLY {}
		LONG ID_CIF_BUILD_MODE
		{
			CUSTOMGUI QUICKTABRADIO;
			CYCLE
			{
				ID_CIF_BUILD_MODE_BALLSTICK;
				ID_CIF_BUILD_MODE_STICK;
			}
		}

	}
}
