CONTAINER Ocifreader
{
	NAME Ocifreader;
	INCLUDE Obase;
	GROUP ID_OBJECTPROPERTIES
	{
		FILENAME ID_CIF_PATH {}
		LONG ID_CIF_A_MIN { MIN -100; MAX 100; STEP 1;}
		LONG ID_CIF_A_MAX { MIN -100; MAX 100; STEP 1;}
		LONG ID_CIF_B_MIN { MIN -100; MAX 100; STEP 1;}
		LONG ID_CIF_B_MAX { MIN -100; MAX 100; STEP 1;}
		LONG ID_CIF_C_MIN { MIN -100; MAX 100; STEP 1;}
		LONG ID_CIF_C_MAX { MIN -100; MAX 100; STEP 1;}
		BUTTON ID_CIF_UPDATE {}
//		BOOL ID_CHANGE {HIDDEN;}
		REAL ID_CIF_ATOM_RADIUS_SCALE { MIN 0.0; MAX 5.0; STEP 0.1;}
		LONG ID_CIF_ATOM_SEGMENTS { MIN 3; MAX 50;}
		REAL ID_CIF_BOND_RADIUS { MIN 0.0; MAX 5.0; STEP 0.1;}
		LONG ID_CIF_BUILD_MODE
		{
			CUSTOMGUI QUICKTABRADIO;
			CYCLE
			{
				ID_CIF_BUILD_MODE_POLY;
				ID_CIF_BUILD_MODE_BALLSTICK;
				ID_CIF_BUILD_MODE_BALL;
				ID_CIF_BUILD_MODE_STICK;
			}
		}

	}
	GROUP ID_SHOW
	{
		BOOL ID_SHOW_ATOM {}
		BOOL ID_SHOW_BOND {}
		BOOL ID_SHOW_POLY {}
	}
}
