CONTAINER Omolreader
{
	NAME Omolreader;
	INCLUDE Obase;
	GROUP ID_OBJECTPROPERTIES
	{
		FILENAME ID_MOL_PATH { }
		BUTTON ID_MOL_UPDATE {}
//		BOOL ID_CHANGE {HIDDEN;}
		REAL ID_MOL_ATOM_RADIUS_SCALE { MIN 0.0; MAX 5.0; STEP 0.1;}
		LONG ID_MOL_ATOM_SEGMENTS { MIN 3; MAX 50;}
		REAL ID_MOL_BOND_RADIUS { MIN 0.0; MAX 5.0; STEP 0.1;}
		LONG ID_MOL_BUILD_MODE
		{
			CUSTOMGUI QUICKTABRADIO;
			CYCLE
			{
				ID_MOL_BUILD_MODE_BALLSTICK;
				ID_MOL_BUILD_MODE_BALL;
				ID_MOL_BUILD_MODE_STICK;
			}
		}
	}

}
