#ifndef _Omolreader_H_
#define _Omolreader_H_

enum
{
	ID_MOL_PATH = 1000,
	ID_MOL_UPDATE = 1001,
	ID_MOL_ATOM_RADIUS_SCALE = 1002,
	ID_MOL_ATOM_SEGMENTS = 1003,
	ID_MOL_BOND_RADIUS = 1004,
	ID_MOL_BUILD_MODE = 1005,
		ID_MOL_BUILD_MODE_BALLSTICK = 0,
		ID_MOL_BUILD_MODE_BALL = 1,
		ID_MOL_BUILD_MODE_STICK = 2,
	
};

#endif